import { describe, it, expect, vi, beforeEach, afterEach } from "vitest";

// ---------------------------------------------------------------------------
// Security test stubs for: SpecGuard Core – File Reader Abstraction
// Module: specguard-core/reader
// Generated by SpecGuard – OWASP Top 10 annotated
// ---------------------------------------------------------------------------

// Lazy import so individual tests can mock the module before resolution.
let reader: typeof import("../../src/core/reader.js");

beforeEach(async () => {
  vi.resetModules();
  reader = await import("../../src/core/reader.js");
});

afterEach(() => {
  vi.restoreAllMocks();
});

// ---------------------------------------------------------------------------
// Path-Traversal (readFile)
// ---------------------------------------------------------------------------

describe("readFile – path-traversal hardening", () => {
  // OWASP A01: Broken Access Control
  it("should not resolve paths that escape the working directory via ../", async () => {
    const traversalPath = "../../../etc/passwd";
    await expect(reader.readFile(traversalPath)).rejects.toThrow();
  });

  // OWASP A01: Broken Access Control
  it("should not resolve paths that escape via URL-encoded traversal sequences (%2e%2e%2f)", async () => {
    const encodedTraversal = "%2e%2e%2f%2e%2e%2fetc%2fpasswd";
    await expect(reader.readFile(encodedTraversal)).rejects.toThrow();
  });

  // OWASP A01: Broken Access Control
  it("should not resolve paths that escape via double-encoded traversal sequences (%252e%252e%252f)", async () => {
    const doubleEncoded = "%252e%252e%252f%252e%252e%252fetc%252fshadow";
    await expect(reader.readFile(doubleEncoded)).rejects.toThrow();
  });

  // OWASP A01: Broken Access Control
  it("should not resolve absolute paths outside the permitted root", async () => {
    const absolutePath = "/etc/passwd";
    await expect(reader.readFile(absolutePath)).rejects.toThrow();
  });

  // OWASP A01: Broken Access Control
  it("should not resolve Windows-style path-traversal sequences (..\\ variants)", async () => {
    const windowsTraversal = "..\\..\\windows\\system32\\drivers\\etc\\hosts";
    await expect(reader.readFile(windowsTraversal)).rejects.toThrow();
  });

  // OWASP A01: Broken Access Control
  it("should not resolve null-byte injected paths", async () => {
    const nullBytePath = "legitimate-file\x00../../etc/passwd";
    await expect(reader.readFile(nullBytePath)).rejects.toThrow();
  });

  // OWASP A01: Broken Access Control
  it("should not resolve paths with mixed slash traversal (....//....//)", async () => {
    const mixedSlash = "....//....//etc/passwd";
    await expect(reader.readFile(mixedSlash)).rejects.toThrow();
  });

  // OWASP A01: Broken Access Control
  it("should not resolve UNC paths on Windows (\\\\server\\share)", async () => {
    const uncPath = "\\\\attacker-server\\share\\secret";
    await expect(reader.readFile(uncPath)).rejects.toThrow();
  });
});

// ---------------------------------------------------------------------------
// Path-Traversal (fileExists)
// ---------------------------------------------------------------------------

describe("fileExists – path-traversal hardening", () => {
  // OWASP A01: Broken Access Control
  it("should not confirm existence of files outside permitted root via ../", async () => {
    const traversalPath = "../../../etc/passwd";
    const result = await reader.fileExists(traversalPath).catch(() => false);
    expect(result).toBe(false);
  });

  // OWASP A01: Broken Access Control
  it("should not confirm existence of absolute paths outside permitted root", async () => {
    const absolutePath = "/etc/shadow";
    const result = await reader.fileExists(absolutePath).catch(() => false);
    expect(result).toBe(false);
  });

  // OWASP A01: Broken Access Control
  it("should not confirm existence of null-byte injected paths", async () => {
    const nullBytePath = "file\x00../../etc/passwd";
    const result = await reader.fileExists(nullBytePath).catch(() => false);
    expect(result).toBe(false);
  });

  // OWASP A01: Broken Access Control
  it("should not confirm existence of URL-encoded traversal paths", async () => {
    const encodedPath = "%2e%2e%2fetc%2fpasswd";
    const result = await reader.fileExists(encodedPath).catch(() => false);
    expect(result).toBe(false);
  });
});

// ---------------------------------------------------------------------------
// Input Validation – Malformed / Dangerous Inputs
// ---------------------------------------------------------------------------

describe("readFile – malformed and dangerous input handling", () => {
  // OWASP A03: Injection
  it("should reject empty string paths", async () => {
    await expect(reader.readFile("")).rejects.toThrow();
  });

  // OWASP A03: Injection
  it("should reject null as a path argument", async () => {
    // @ts-expect-error – intentional invalid input for security test
    await expect(reader.readFile(null)).rejects.toThrow();
  });

  // OWASP A03: Injection
  it("should reject undefined as a path argument", async () => {
    // @ts-expect-error – intentional invalid input for security test
    await expect(reader.readFile(undefined)).rejects.toThrow();
  });

  // OWASP A03: Injection
  it("should reject non-string path arguments (number)", async () => {
    // @ts-expect-error – intentional invalid input for security test
    await expect(reader.readFile(42)).rejects.toThrow();
  });

  // OWASP A03: Injection
  it("should reject non-string path arguments (object)", async () => {
    // @ts-expect-error – intentional invalid input for security test
    await expect(reader.readFile({ path: "/etc/passwd" })).rejects.toThrow();
  });

  // OWASP A03: Injection
  it("should reject excessively long path strings (potential buffer-overflow vector)", async () => {
    const longPath = "a".repeat(65536);
    await expect(reader.readFile(longPath)).rejects.toThrow();
  });

  // OWASP A03: Injection
  it("should reject paths containing shell metacharacters", async () => {
    const shellPath = "file; rm -rf /";
    await expect(reader.readFile(shellPath)).rejects.toThrow();
  });

  // OWASP A03: Injection
  it("should reject paths containing backtick command substitution", async () => {
    const backtickPath = "`cat /etc/passwd`";
    await expect(reader.readFile(backtickPath)).rejects.toThrow();
  });
});

describe("fileExists – malformed and dangerous input handling", () => {
  // OWASP A03: Injection
  it("should reject empty string paths", async () => {
    const result = await reader.fileExists("").catch(() => false);
    expect(result).toBe(false);
  });

  // OWASP A03: Injection
  it("should reject null as a path argument", async () => {
    // @ts-expect-error – intentional invalid input for security test
    const result = await reader.fileExists(null).catch(() => false);
    expect(result).toBe(false);
  });

  // OWASP A03: Injection
  it("should reject undefined as a path argument", async () => {
    // @ts-expect-error – intentional invalid input for security test
    const result = await reader.fileExists(undefined).catch(() => false);
    expect(result).toBe(false);
  });
});

// ---------------------------------------------------------------------------
// Sensitive Data Exposure – module must not leak secrets in errors
// ---------------------------------------------------------------------------

describe("readFile – error message information disclosure", () => {
  // OWASP A02: Cryptographic Failures / OWASP A05: Security Misconfiguration
  it("should not expose absolute filesystem paths in thrown error messages", async () => {
    try {
      await reader.readFile("nonexistent-file.txt");
    } catch (err: unknown) {
      if (err instanceof Error) {
        // Error messages must not reveal server-side absolute paths
        expect(err.message).not.toMatch(/^\/(?:home|root|var|usr|etc)\//);
        expect(err.message).not.toMatch(/C:\\Users\\/i);
      }
    }
  });

  // OWASP A02: Cryptographic Failures / OWASP A05: Security Misconfiguration
  it("should not expose internal stack frames referencing sensitive system paths in the error object", async () => {
    try {
      await reader.readFile("../../../etc/passwd");
    } catch (err: unknown) {
      if (err instanceof Error && err.stack) {
        expect(err.stack).not.toMatch(/\/etc\/passwd/);
      }
    }
  });
});

describe("fileExists – error message information disclosure", () => {
  // OWASP A02: Cryptographic Failures / OWASP A05: Security Misconfiguration
  it("should not expose absolute filesystem paths when returning false for traversal paths", async () => {
    let caughtError: Error | undefined;
    try {
      await reader.fileExists("../../../etc/passwd");
    } catch (err: unknown) {
      if (err instanceof Error) {
        caughtError = err;
      }
    }
    if (caughtError) {
      expect(caughtError.message).not.toMatch(/\/etc\/passwd/);
    }
  });
});

// ---------------------------------------------------------------------------
// Denial of Service – resource exhaustion vectors
// ---------------------------------------------------------------------------

describe("readFile – denial-of-service hardening", () => {
  // OWASP A05: Security Misconfiguration
  it("should complete or reject within a reasonable timeout for a deeply nested path", async () => {
    const deepPath = Array(512).fill("dir").join("/") + "/file.txt";
    const raceTimeout = new Promise<never>((_, reject) =>
      setTimeout(() => reject(new Error("timeout")), 5000)
    );
    await expect(
      Promise.race([reader.readFile(deepPath), raceTimeout])
    ).rejects.toThrow();
  });

  // OWASP A05: Security Misconfiguration
  it("should complete or reject within a reasonable timeout for a path with many repeated traversal segments", async () => {
    const manyTraversals = "../".repeat(1000) + "etc/passwd";
    const raceTimeout = new Promise<never>((_, reject) =>
      setTimeout(() => reject(new Error("timeout")), 5000)
    );
    await expect(
      Promise.race([reader.readFile(manyTraversals), raceTimeout])
    ).rejects.toThrow();
  });
});

// ---------------------------------------------------------------------------
// No Authentication / Authorisation – caller responsibility boundary
// ---------------------------------------------------------------------------

describe("module contract – no auth/authz performed internally", () => {
  // OWASP A01: Broken Access Control
  it("readFile should not silently succeed when given a path outside the spec-permitted boundary (caller must enforce)", async () => {
    // The module itself must either enforce boundaries or throw; it must never
    // silently return content for a clearly out-of-bounds path.
    const outOfBounds = "../../secret.env";
    let succeeded = false;
    try {
      await reader.readFile(outOfBounds);
      succeeded = true;
    } catch {
      succeeded = false;
    }
    // If the module has no internal boundary enforcement it MUST throw,
    // ensuring callers cannot accidentally bypass checks.
    expect(succeeded).toBe(false);
  });

  // OWASP A01: Broken Access Control
  it("fileExists should not silently return true for a path outside the spec-permitted boundary", async () => {
    const outOfBounds = "../../secret.env";
    let result: boolean | undefined;
    try {
      result = await reader.fileExists(outOfBounds);
    } catch {
      result = false;
    }
    expect(result).toBe(false);
  });
});
