/**
 * Shared plan-writer utility.
 *
 * Every pipeline that detects issues can call `writePlan` to produce a
 * Markdown file under `.specguard/plans/` that coding agents (Claude, Cursor,
 * Copilot) can consume directly to fix the problem.
 *
 * File naming: `.specguard/plans/<pipeline>-<YYYYMMDD-HHmmss>.md`
 *
 * Format:
 *   ---
 *   pipeline: <name>
 *   generatedAt: <ISO>
 *   ---
 *
 *   # <title>
 *
 *   > <summary>
 *
 *   ## <section heading>
 *   - item 1
 *   - item 2
 *
 *   ...
 */
import fs from 'node:fs';
import path from 'node:path';

export interface PlanSection {
  heading: string;
  /** Markdown list items — written as `- item`. Pass pre-formatted text when needed. */
  items: string[];
  /** If true, render as an ordered list instead of bullets. */
  ordered?: boolean;
}

export interface PlanOpts {
  /** Pipeline that produced the findings, e.g. `drift`. */
  pipeline: string;
  /** Short title for the plan document. */
  title: string;
  /** 1–3 sentence summary of what was found and the overall fix approach. */
  summary: string;
  /** Structured sections: findings, fix steps, files to edit, etc. */
  sections: PlanSection[];
  /** Absolute path to the project root (used to resolve the plans dir). */
  rootDir: string;
}

/**
 * Write a Markdown plan file to `.specguard/plans/<pipeline>-<timestamp>.md`.
 * Returns the absolute path to the written file.
 */
export function writePlan(opts: PlanOpts): string {
  const ts = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
  const plansDir = path.join(opts.rootDir, '.specguard', 'plans');
  fs.mkdirSync(plansDir, { recursive: true });

  const filePath = path.join(plansDir, `${opts.pipeline}-${ts}.md`);

  const lines: string[] = [
    '---',
    `pipeline: ${opts.pipeline}`,
    `generatedAt: ${new Date().toISOString()}`,
    '---',
    '',
    `# ${opts.title}`,
    '',
    `> ${opts.summary}`,
    '',
  ];

  for (const section of opts.sections) {
    if (section.items.length === 0) continue;
    lines.push(`## ${section.heading}`, '');
    if (section.ordered) {
      section.items.forEach((item, i) => lines.push(`${i + 1}. ${item}`));
    } else {
      for (const item of section.items) lines.push(`- ${item}`);
    }
    lines.push('');
  }

  lines.push(
    '---',
    '',
    `_Generated by SpecGuard \`${opts.pipeline}\` pipeline · ${new Date().toISOString()}_`,
    `_Pass this file to your coding agent to apply the fixes automatically._`,
  );

  fs.writeFileSync(filePath, lines.join('\n'));
  return filePath;
}
