/**
 * Generated run state. These files are rewritten by pipeline runs, differ per
 * machine (or per run), and do not belong in version control. Configuration,
 * rules, plans, replay recordings, and the proof ledger are not listed.
 *
 * Spec: specs/cli/commands/init.md
 */

/** Paths relative to the repo root, as `.gitignore` patterns. */
export const GENERATED_STATE_PATHS = [
  '.specguard/.env',
  '.specguard/activity-log.json',
  '.specguard/analysis.json',
  '.specguard/alignment.json',
  '.specguard/code-quality.json',
  '.specguard/dep-check.json',
  '.specguard/drift-registry.json',
  '.specguard/gaps.json',
  '.specguard/security.json',
  '.specguard/llm-usage.json',
  '.specguard/traceability.json',
  '.specguard/traceability.csv',
  '.specguard/contracts.json',
  '.specguard/auth/',
  '.specguard/evidence/',
  '.specguard/runs/',
];

export const IGNORE_START = '# specguard:generated-state:start';
export const IGNORE_END = '# specguard:generated-state:end';

export function renderIgnoreBlock(): string {
  return [IGNORE_START, '# Generated by SpecGuard runs. Edit config, rules, plans and specs, not these.', ...GENERATED_STATE_PATHS, IGNORE_END, ''].join('\n');
}

/**
 * Add or refresh the managed block in `.gitignore` text. Lines outside the block
 * are untouched. A second call with the result returns it unchanged.
 */
export function applyIgnoreBlock(existing: string): string {
  const block = renderIgnoreBlock();
  const start = existing.indexOf(IGNORE_START);
  const end = existing.indexOf(IGNORE_END);
  if (start !== -1 && end > start) {
    const after = existing.slice(end + IGNORE_END.length).replace(/^\r?\n/, '');
    return existing.slice(0, start) + block + after;
  }
  const base = existing.length === 0 || existing.endsWith('\n') ? existing : `${existing}\n`;
  return `${base}${base.length > 0 ? '\n' : ''}${block}`;
}
